openapi: 3.0.0
info:
    title: Microsoft Graph API Plugin to access data from Entra ID and Identity Protection information
    description: Specification to retrieve information via MIcrosoft Graph API for Entra Identity Protection to be used in Security Copilot.
    version: "1.0"
servers:
    - url: https://graph.microsoft.com/v1.0
paths:
    /identity/identityProtection/riskyUsers:
        get: 
            operationId: riskyUsers
            summary: Get a list of the riskyUser objects and their properties. 
            responses:
                200:
                  description: Successful retrieval. 
                401:
                  description: Unsuccessful authentication.
