openapi: 3.0.0
info:
  title: Microsoft Graph API
  version: 1.0.0
paths:
  /identityGovernance/entitlementManagement/accessPackages:
    get:
      summary: List accessPackages
      description: Retrieve a list of accessPackage objects.
      operationId: listAccessPackages
      parameters:
      - name: $filter
        in: query
        description: Filter items by property values
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Order items by property values
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Select properties to be returned
        required: false
        schema:
          type: string
      - name: $expand
        in: query
        description: Expand related entities
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Show only the first n items
        required: false
        schema:
          type: integer
      - name: $skip
        in: query
        description: Skip the first n items
        required: false
        schema:
          type: integer
      - name: $count
        in: query
        description: Include count of items
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Successful retrieval of accessPackage objects
