openapi: 3.0.0
info:
    title: Microsoft Graph API Plugin to access data from Entra ID and Conditional Access Policies
    description: Specification to retrieve information from the Graph API for Conditional Access Policies to be used in Copilot for Security.
    version: "1.0"
servers:
    - url: https://graph.microsoft.com/v1.0
paths:
    /identity/conditionalAccess/policies:
        get: 
            operationId: ListCAPolicies
            summary: List all Entra ID Conditional Access Policies. 
            responses:
                200:
                  description: Successful retrieval. 
                401:
                  description: Unsuccessful authentication.
