openapi: 3.0.1
info:
  title: Microsoft Graph API - List fido2AuthenticationMethod
  description: Retrieve a list of a user's fido2AuthenticationMethod objects and their properties.
  version: 1.0.0
paths:
  /me/authentication/fido2Methods:
    get:
      summary: List fido2AuthenticationMethods for the signed-in user
      description: Retrieve the details of your own FIDO2 authentication methods.
      responses:
        '200':
          description: A collection of fido2AuthenticationMethod objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fido2AuthenticationMethod'
  /users/{id}/authentication/fido2Methods:
    get:
      summary: List fido2AuthenticationMethods for a user
      description: Retrieve the details of your own or another user's FIDO2 authentication methods.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A collection of fido2AuthenticationMethod objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fido2AuthenticationMethod'
components:
  schemas:
    fido2AuthenticationMethod:
      type: object
      properties:
        id:
          type: string
          description: The authentication method identifier.
        displayName:
          type: string
          description: The display name of the key as given by the user.
        creationDateTime:
          type: string
          format: date-time
          description: The timestamp when this key was registered to the user.
        aaGuid:
          type: string
          description: Authenticator Attestation GUID, an identifier that indicates the type (e.g. make and model) of the authenticator.
        model:
          type: string
          description: The manufacturer-assigned model of the FIDO2 security key.
        attestationCertificates:
          type: array
          items:
            type: string
          description: The attestation certificate(s) attached to this security key.
