openapi: 3.0.0
info:
    title: Microsoft Graph API Plugin to access data from Entra ID and Identity Protection information
    description: Specification to retrieve information via MIcrosoft Graph API for Entra Identity Protection to be used in Security Copilot.
    version: "1.0"
servers:
    - url: https://graph.microsoft.com/v1.0
paths:
    /identityProtection/riskyUsers:
        get: 
            operationId: riskyUsers
            summary: Get a list of the riskyUser objects and their properties. 
            responses:
                200:
                  description: Successful retrieval. 
                401:
                  description: Unsuccessful authentication.
                  
    /identityProtection/riskDetections:
        get: 
            operationId: riskDetections
            summary: Get a list of the riskDetection objects and their properties. 
            responses:
                200:
                  description: Successful retrieval. 
                401:
                  description: Unsuccessful authentication.
                  
    /identityProtection/riskyUsers/{userId}/history:
        get:
          summary: Get the riskyUserHistoryItems from the history navigation property.
          parameters:
            - name: userId
              in: path
              required: true
              description: The ID of the user.
              schema:
                type: string
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/riskyUserHistoryItem'
            '400':
              description: Bad request
            '401':
              description: Unauthorized
            '403':
              description: Forbidden
            '404':
              description: Not found
    components:
      schemas:
        riskyUserHistoryItem:
          type: object
          properties:
            id:
              type: string
              description: The unique identifier for the riskyUserHistoryItem object.
            isDeleted:
              type: boolean
              description: Indicates whether the user is deleted.
            isProcessing:
              type: boolean
              description: Indicates whether a user's risky state is being processed by the backend.
            riskLastUpdatedDateTime:
              type: string
              format: date-time
              description: The date and time when the risky user was last updated.
            riskLevel:
              type: string
              description: Level of the detected risky user.
              enum:
                - low
                - medium
                - high
                - hidden
                - none
                - unknownFutureValue
            riskState:
              type: string
              description: State of the user's risk.
              enum:
                - none
                - confirmedSafe
                - remediated
                - dismissed
                - atRisk
                - confirmedCompromised
                - unknownFutureValue
            riskDetail:
              type: string
              description: Details of the detected risk.
              enum:
                - none
                - adminGeneratedTemporaryPassword
                - userPerformedSecuredPasswordChange
                - userPerformedSecuredPasswordReset
                - adminConfirmedSigninSafe
                - aiConfirmedSigninSafe
                - userPassedMFADrivenByRiskBasedPolicy
                - adminDismissedAllRiskForUser
                - adminConfirmedSigninCompromised
                - hidden
                - adminConfirmedUserCompromised
                - unknownFutureValue
            userDisplayName:
              type: string
              description: Risky user display name.
            userPrincipalName:
              type: string
              description: Risky user principal name.
            userId:
              type: string
              description: The ID of the user.
            initiatedBy:
              type: string
              description: The ID of actor that does the operation.
            activity:
              type: object
              description: The activity related to user risk level change.
