openapi: 3.0.1
info:
  title: Microsoft Graph API - fido2AuthenticationMethod
  description: A representation of a FIDO2 security key registered to a user. FIDO2 is a sign-in authentication method.
  version: 1.0.0
paths:
  /users/{userId}/authentication/fido2Methods:
    get:
      summary: List fido2AuthenticationMethods
      description: Retrieve a list of a user's fido2AuthenticationMethod objects and their properties.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A collection of fido2AuthenticationMethod objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/fido2AuthenticationMethod'
  /users/{userId}/authentication/fido2Methods/{id}:
    get:
      summary: Get fido2AuthenticationMethod
      description: Read the properties and relationships of a user's fido2AuthenticationMethod object.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A fido2AuthenticationMethod object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fido2AuthenticationMethod'
    delete:
      summary: Delete fido2AuthenticationMethod
      description: Deletes a user's fido2AuthenticationMethod object.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content.
components:
  schemas:
    fido2AuthenticationMethod:
      type: object
      properties:
        aaGuid:
          type: string
          description: Authenticator Attestation GUID, an identifier that indicates the type (e.g. make and model) of the authenticator.
        attestationCertificates:
          type: array
          items:
            type: string
          description: The attestation certificate(s) attached to this security key.
        attestationLevel:
          type: string
          description: The attestation level of this FIDO2 security key. Possible values are: `attested`, or `notAttested`.
        createdDateTime:
          type: string
          format: date-time
          description: The timestamp when this key was registered to the user.
        displayName:
          type: string
          description: The display name of the key as given by the user.
        id:
          type: string
          description: The authentication method identifier.
        model:
          type: string
